import { Platform, StyleSheet } from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import { fontText } from '../../../utils/fonts';

export const ARCHIVE_COLORS = {
  bg: '#FFFFFF',
  card: '#FFFFFF',
  border: '#E5E7EB',
  text: '#111827',
  muted: '#6B7280',
  faint: '#9CA3AF',
  primary: '#0000FF',
  navy: '#1B2B6B',
  danger: '#DC2626',
  thumbBg: '#F3F4F6',
};

export const archivesStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: ARCHIVE_COLORS.bg },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp('8%'),
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    minHeight: 48,
  },
  headerTitle: {
    ...fontText.semibold13,
    fontSize: 17,
    color: ARCHIVE_COLORS.text,
    flex: 1,
    textAlign: 'center',
  },
  headerBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerSubtitle: {
    ...fontText.regular12,
    fontSize: 12,
    color: ARCHIVE_COLORS.muted,
    textAlign: 'center',
    paddingBottom: 10,
  },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: wp('5%'),
    marginBottom: 10,
  },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: ARCHIVE_COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 12 : 8,
    ...fontText.regular12,
    fontSize: 14,
    color: ARCHIVE_COLORS.text,
    backgroundColor: '#FFF',
  },
  sortBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: ARCHIVE_COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listContent: {
    paddingHorizontal: wp('5%'),
    paddingBottom: hp('4%'),
  },
  emptyBody: {
    ...fontText.regular12,
    fontSize: 14,
    color: ARCHIVE_COLORS.muted,
    textAlign: 'center',
    marginTop: 40,
    lineHeight: 20,
  },
  errorText: {
    ...fontText.medium13,
    color: ARCHIVE_COLORS.danger,
    textAlign: 'center',
    marginBottom: 12,
  },
  card: {
    flexDirection: 'row',
    gap: 12,
    borderWidth: 1,
    borderColor: ARCHIVE_COLORS.border,
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    backgroundColor: ARCHIVE_COLORS.card,
  },
  cardBusy: { opacity: 0.55 },
  thumb: {
    width: 92,
    height: 78,
    borderRadius: 12,
    backgroundColor: ARCHIVE_COLORS.thumbBg,
  },
  cardBody: { flex: 1, minWidth: 0 },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cardTitle: {
    ...fontText.semibold13,
    fontSize: 14,
    color: ARCHIVE_COLORS.text,
    flex: 1,
  },
  archivedPill: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: '#F1F5F9',
  },
  archivedPillText: {
    ...fontText.semibold13,
    fontSize: 10,
    color: ARCHIVE_COLORS.muted,
  },
  cardCategory: {
    ...fontText.regular12,
    fontSize: 12,
    color: ARCHIVE_COLORS.muted,
    marginTop: 2,
  },
  cardPrice: {
    ...fontText.bold13,
    fontSize: 14,
    color: ARCHIVE_COLORS.text,
    marginTop: 4,
  },
  cardMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 4,
  },
  cardMetaText: {
    ...fontText.regular12,
    fontSize: 11,
    color: ARCHIVE_COLORS.faint,
  },
  menuBtn: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-start',
  },
  footerLoader: { marginVertical: 16 },
});
