import { Platform, StyleSheet } from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

export const AUTH_COLORS = {
  gradientStart: '#1A00FF',
  gradientMid: '#6B1BFF',
  gradientEnd: '#C400FF',
  cardBg: '#FFFFFF',
  heading: '#0B1534',
  subtitle: '#5B6F8E',
  sectionTitle: '#111827',
  inputBg: '#F4F6FB',
  inputBorder: '#E8EDF5',
  inputBorderFocus: '#1E4DFF',
  placeholder: '#9AA8BC',
  primaryButton: '#0044FF',
  primaryButtonEnd: '#1E4DFF',
  dividerText: '#7A8DA8',
  dividerLine: '#E2E8F0',
  guestText: '#0044FF',
  error: '#DC2626',
  icon: '#8B9AB5',
  toggleTrack: '#F0F3F9',
  toggleInactiveText: '#4A5C78',
};

export const AUTH_SPACING = {
  xs: hp('0.6%'),
  sm: hp('1%'),
  md: hp('1.6%'),
  lg: hp('2.2%'),
  xl: hp('3%'),
};

export const AUTH_RADIUS = {
  input: wp('3.2%'),
  card: wp('9%'),
  button: wp('14%'),
  social: wp('3.5%'),
};

export const loginScreenStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: AUTH_COLORS.gradientEnd,
  },
  headerSection: {
    flex: 0.34,
    minHeight: hp('30%'),
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: hp('2%'),
  },
  logoWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  slogan: {
    alignSelf: 'center',
  },
  cardSection: {
    flex: 0.66,
    minHeight: hp('54%'),
    marginTop: -hp('2.5%'),
  },
  card: {
    flex: 1,
    backgroundColor: AUTH_COLORS.cardBg,
    borderTopLeftRadius: AUTH_RADIUS.card,
    borderTopRightRadius: AUTH_RADIUS.card,
    paddingHorizontal: wp('6.5%'),
    paddingTop: hp('3.5%'),
    paddingBottom: hp('2%'),
    ...Platform.select({
      ios: {
        shadowColor: '#0B1534',
        shadowOffset: { width: 0, height: -8 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
      },
      android: {
        elevation: 18,
      },
    }),
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: hp('3%'),
  },
  welcomeTitle: {
    fontSize: wp('8%'),
    fontWeight: '800',
    color: AUTH_COLORS.heading,
    lineHeight: wp('9.5%'),
    letterSpacing: -0.3,
  },
  welcomeSubtitle: {
    marginTop: hp('0.8%'),
    marginBottom: hp('2.4%'),
    fontSize: wp('3.7%'),
    lineHeight: wp('5.2%'),
    color: AUTH_COLORS.subtitle,
    fontWeight: '500',
  },
  sectionTitle: {
    marginTop: AUTH_SPACING.lg,
    marginBottom: AUTH_SPACING.md,
    fontSize: wp('4.8%'),
    fontWeight: '800',
    color: AUTH_COLORS.sectionTitle,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: AUTH_COLORS.inputBg,
    borderWidth: 1,
    borderColor: AUTH_COLORS.inputBorder,
    borderRadius: AUTH_RADIUS.input,
    paddingHorizontal: wp('3.8%'),
    minHeight: hp('6.8%'),
    marginBottom: AUTH_SPACING.md,
  },
  inputRowFocused: {
    borderColor: AUTH_COLORS.inputBorderFocus,
    backgroundColor: '#FFFFFF',
  },
  inputIcon: {
    marginRight: wp('2.5%'),
  },
  input: {
    flex: 1,
    fontSize: wp('3.8%'),
    color: AUTH_COLORS.heading,
    paddingVertical: Platform.OS === 'ios' ? hp('1.4%') : hp('1%'),
  },
  otpButton: {
    alignSelf: 'flex-start',
    paddingVertical: AUTH_SPACING.xs,
    marginBottom: AUTH_SPACING.sm,
  },
  otpButtonText: {
    fontSize: wp('3.6%'),
    fontWeight: '700',
    color: AUTH_COLORS.primaryButton,
  },
  orRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: AUTH_SPACING.md,
  },
  orLine: {
    flex: 1,
    height: 1,
    backgroundColor: AUTH_COLORS.dividerLine,
  },
  orText: {
    marginHorizontal: wp('3%'),
    fontSize: wp('3.4%'),
    fontWeight: '700',
    color: AUTH_COLORS.dividerText,
  },
  toggleText: {
    alignSelf: 'flex-end',
    marginTop: -AUTH_SPACING.sm,
    marginBottom: AUTH_SPACING.md,
    fontSize: wp('3.4%'),
    fontWeight: '600',
    color: AUTH_COLORS.primaryButton,
  },
  primaryButtonWrap: {
    marginTop: hp('0.6%'),
    borderRadius: AUTH_RADIUS.button,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: AUTH_COLORS.primaryButton,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.28,
        shadowRadius: 14,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  primaryButton: {
    borderRadius: AUTH_RADIUS.button,
    minHeight: hp('6.6%'),
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: wp('4.3%'),
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  errorText: {
    marginTop: AUTH_SPACING.sm,
    marginBottom: AUTH_SPACING.sm,
    fontSize: wp('3.4%'),
    fontWeight: '600',
    color: AUTH_COLORS.error,
    textAlign: 'center',
  },
  socialDividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp('3%'),
    marginBottom: hp('2.4%'),
  },
  socialDividerText: {
    marginHorizontal: wp('2.5%'),
    fontSize: wp('3.15%'),
    color: AUTH_COLORS.dividerText,
    fontWeight: '500',
    textAlign: 'center',
    flexShrink: 1,
    lineHeight: wp('4.4%'),
  },
  socialRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: wp('5%'),
    marginBottom: hp('2.8%'),
  },
  socialButton: {
    width: wp('15%'),
    height: wp('15%'),
    borderRadius: AUTH_RADIUS.social,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: AUTH_COLORS.dividerLine,
    ...Platform.select({
      ios: {
        shadowColor: '#0B1534',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  socialButtonDisabled: {
    opacity: 0.6,
  },
  guestButton: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: AUTH_SPACING.sm,
    paddingHorizontal: wp('2%'),
  },
  guestText: {
    fontSize: wp('3.7%'),
    fontWeight: '700',
    color: AUTH_COLORS.guestText,
  },
  guestArrow: {
    marginLeft: 4,
  },
  registerText: {
    fontSize: wp('3.9%'),
    fontWeight: '600',
    color: AUTH_COLORS.primaryButton,
    justifyContent: 'center',
    alignSelf: 'center',
    paddingVertical: 24,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    gap: 10,
    marginBottom: 16,
  },
  countryBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: AUTH_COLORS.inputBg,
    borderWidth: 1,
    borderColor: AUTH_COLORS.inputBorder,
    borderRadius: AUTH_RADIUS.input,
    paddingHorizontal: wp('3.5%'),
    minHeight: hp('6.9%'),
    marginBottom: AUTH_SPACING.md,
  },
  flag: {
    fontSize: wp('5.2%'),
  },
  code: {
    marginLeft: 5,
    fontWeight: '500',
    color: '#919BBA',
  },
  inputBoxMobile: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: AUTH_COLORS.inputBg,
    borderWidth: 1,
    borderColor: AUTH_COLORS.inputBorder,
    borderRadius: AUTH_RADIUS.input,
    paddingHorizontal: wp('3.5%'),
    minHeight: hp('6.9%'),
    marginBottom: AUTH_SPACING.md,
  },
  channelToggleRow: {
    flexDirection: 'row',
    backgroundColor: AUTH_COLORS.toggleTrack,
    borderRadius: AUTH_RADIUS.input,
    padding: 4,
    marginBottom: hp('2%'),
  },
  channelToggleButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp('1.45%'),
    borderRadius: AUTH_RADIUS.input - 2,
  },
  channelToggleButtonActive: {
    backgroundColor: AUTH_COLORS.primaryButton,
    ...Platform.select({
      ios: {
        shadowColor: AUTH_COLORS.primaryButton,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  channelToggleText: {
    fontSize: wp('3.65%'),
    fontWeight: '600',
    color: AUTH_COLORS.toggleInactiveText,
  },
  channelToggleTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  alreadyRegisteredBanner: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: AUTH_RADIUS.input,
    paddingHorizontal: wp('3.5%'),
    paddingVertical: hp('1.4%'),
    marginBottom: AUTH_SPACING.md,
  },
  alreadyRegisteredText: {
    fontSize: wp('3.4%'),
    lineHeight: wp('5%'),
    color: '#B91C1C',
    fontWeight: '500',
  },
  phoneInputDivider: {
    fontSize: wp('3.8%'),
    color: AUTH_COLORS.placeholder,
    marginRight: wp('1.5%'),
    fontWeight: '500',
  },
  inlineCountryPicker: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: wp('2%'),
    marginRight: wp('0.5%'),
  },
  inlineCountryCode: {
    marginLeft: 4,
    fontWeight: '600',
    color: AUTH_COLORS.heading,
    fontSize: wp('3.8%'),
  },
});
