import { Platform, StyleSheet } from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import { fontText } from '../../../utils/fonts';

export const CART_COLORS = {
  bg: '#FFFFFF',
  title: '#1B2B6B',
  secureTitle: '#2C4AA8',
  text: '#111827',
  muted: '#6B7280',
  meta: '#8B95B5',
  border: '#E5EAF6',
  cardBorder: '#C7D2FE',
  cardBg: '#F5F8FF',
  priceBlue: '#1B2B6B',
  primary: '#0000FF',
  link: '#2563EB',
  bullet: '#4F6BFF',
  divider: '#E8EDF8',
  checkbox: '#0000FF',
  success: '#16A34A',
  chipBg: '#E8ECFB',
  chipBorder: '#C7D2FE',
  inputBg: '#E8E8EA',
};

export const cartCheckoutStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: CART_COLORS.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp('4%'),
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: CART_COLORS.border,
  },
  headerTitle: {
    ...fontText.bold13,
    fontSize: 17,
    color: CART_COLORS.text,
  },
  content: {
    paddingHorizontal: wp('5%'),
    paddingTop: hp('1%'),
    paddingBottom: hp('16%'),
  },
  secureTitle: {
    ...fontText.semibold13,
    fontSize: 20,
    color: CART_COLORS.secureTitle,
    textAlign: 'center',
    marginBottom: hp('2%'),
  },
  sectionHint: {
    ...fontText.medium13,
    fontSize: 14,
    color: CART_COLORS.secureTitle,
    textAlign: 'center',
    marginBottom: hp('1.4%'),
    marginTop: hp('1%'),
  },
  listingCard: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: CART_COLORS.border,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#FFF',
    marginBottom: hp('1.2%'),
    ...Platform.select({
      ios: {
        shadowColor: '#1B2B6B',
        shadowOpacity: 0.05,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 3 },
      },
      android: { elevation: 1 },
    }),
  },
  listingImage: {
    width: wp('28%'),
    minHeight: 108,
    backgroundColor: '#E5E7EB',
  },
  listingBody: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'space-between',
  },
  listingTitle: {
    ...fontText.bold13,
    fontSize: 15,
    color: CART_COLORS.text,
  },
  listingCategory: {
    ...fontText.regular12,
    color: CART_COLORS.muted,
    marginTop: 2,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaText: {
    ...fontText.regular12,
    color: CART_COLORS.meta,
  },
  listingPrice: {
    ...fontText.bold13,
    fontSize: 15,
    color: CART_COLORS.primary,
    textAlign: 'right',
    marginTop: 8,
  },
  serviceCard: {
    borderWidth: 1.5,
    borderColor: CART_COLORS.cardBorder,
    backgroundColor: CART_COLORS.cardBg,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 12,
    marginBottom: hp('2%'),
  },
  serviceHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: CART_COLORS.checkbox,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: CART_COLORS.checkbox,
  },
  serviceTitleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  serviceTitle: {
    ...fontText.bold13,
    fontSize: 15,
    color: CART_COLORS.text,
    flex: 1,
  },
  servicePrice: {
    ...fontText.bold13,
    fontSize: 14,
    color: CART_COLORS.primary,
  },
  serviceDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: CART_COLORS.divider,
    marginVertical: 12,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 6,
  },
  bulletDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: CART_COLORS.bullet,
    marginTop: 6,
  },
  bulletText: {
    ...fontText.regular12,
    color: CART_COLORS.secureTitle,
    flex: 1,
  },
  learnMore: {
    ...fontText.bold13,
    fontSize: 11,
    color: CART_COLORS.link,
    textAlign: 'right',
    marginTop: 8,
    letterSpacing: 0.5,
  },
  editLink: {
    ...fontText.bold13,
    fontSize: 11,
    color: CART_COLORS.link,
    textAlign: 'right',
    marginTop: 8,
    letterSpacing: 0.5,
  },
  conditionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#F3F4F6',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  conditionChipText: {
    ...fontText.regular12,
    color: CART_COLORS.text,
    maxWidth: wp('60%'),
  },
  chipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 4,
  },
  fieldLabel: {
    ...fontText.medium13,
    fontSize: 13,
    color: CART_COLORS.secureTitle,
    marginBottom: 6,
  },
  fieldBox: {
    backgroundColor: CART_COLORS.inputBg,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
  },
  fieldText: {
    ...fontText.regular12,
    color: CART_COLORS.text,
  },
  summaryTitle: {
    ...fontText.bold13,
    fontSize: 18,
    color: CART_COLORS.secureTitle,
    marginTop: hp('1%'),
    marginBottom: hp('1%'),
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  summaryLabel: {
    ...fontText.regular12,
    color: CART_COLORS.secureTitle,
  },
  summaryValue: {
    ...fontText.bold13,
    fontSize: 13,
    color: CART_COLORS.secureTitle,
  },
  discountLink: {
    ...fontText.semibold13,
    fontSize: 13,
    color: CART_COLORS.link,
    marginTop: 8,
  },
  discountInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
  },
  discountInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: CART_COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    ...fontText.regular12,
    color: CART_COLORS.text,
  },
  discountApplyBtn: {
    backgroundColor: CART_COLORS.primary,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  discountApplyText: {
    ...fontText.bold13,
    fontSize: 13,
    color: '#FFF',
  },
  couponApplied: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    backgroundColor: '#ECFDF5',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  couponAppliedText: {
    ...fontText.bold13,
    fontSize: 13,
    color: '#047857',
  },
  totalDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: CART_COLORS.divider,
    marginVertical: 12,
  },
  totalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: hp('1%'),
  },
  totalLabel: {
    ...fontText.bold13,
    fontSize: 16,
    color: CART_COLORS.secureTitle,
  },
  totalValue: {
    ...fontText.bold13,
    fontSize: 18,
    color: CART_COLORS.secureTitle,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: wp('5%'),
    paddingTop: 10,
    backgroundColor: CART_COLORS.bg,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: CART_COLORS.border,
  },
  payBtn: {
    backgroundColor: CART_COLORS.primary,
    borderRadius: 999,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  payBtnText: {
    ...fontText.bold13,
    fontSize: 16,
    color: '#FFF',
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  emptyTitle: {
    ...fontText.bold13,
    fontSize: 18,
    color: CART_COLORS.text,
    marginBottom: 12,
  },
  emptyBtn: {
    backgroundColor: CART_COLORS.primary,
    borderRadius: 999,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  emptyBtnText: {
    ...fontText.bold13,
    color: '#FFF',
  },
});
