import { Platform, StyleSheet } from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

export const CM_COLORS = {
  sheetBg: '#FFFFFF',
  handle: '#D1D5DB',
  title: '#111827',
  text: '#111827',
  muted: '#9CA3AF',
  meta: '#9CA3AF',
  reply: '#9CA3AF',
  inputBg: '#F3F4F6',
  inputPlaceholder: '#9CA3AF',
  border: '#F3F4F6',
  heart: '#111827',
  heartActive: '#FF2D55',
  owner: '#9CA3AF',
  shadow: 'rgba(0,0,0,0.08)',
  skeleton: '#E5E7EB',
  emptyIcon: '#D1D5DB',
};

export const cmStyles = StyleSheet.create({
  handleWrap: {
    alignItems: 'center',
    paddingTop: hp('1.1%'),
    paddingBottom: hp('0.8%'),
  },
  handle: {
    width: wp('11%'),
    height: hp('0.5%'),
    borderRadius: 100,
    backgroundColor: CM_COLORS.handle,
  },
  header: {
    paddingHorizontal: wp('5%'),
    paddingBottom: hp('1.2%'),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: CM_COLORS.border,
    backgroundColor: CM_COLORS.sheetBg,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: hp('5%'),
  },
  headerTitle: {
    fontSize: wp('4.6%'),
    fontWeight: '700',
    color: CM_COLORS.title,
    letterSpacing: -0.2,
  },
  headerCount: {
    fontSize: wp('4.2%'),
    fontWeight: '600',
    color: CM_COLORS.muted,
    marginLeft: 4,
  },
  closeBtn: {
    position: 'absolute',
    right: 0,
    padding: 8,
  },
  listContent: {
    paddingHorizontal: wp('4.5%'),
    paddingTop: hp('1%'),
    paddingBottom: hp('2%'),
  },
  commentRow: {
    flexDirection: 'row',
    paddingVertical: hp('1.4%'),
  },
  replyIndent: {
    marginLeft: wp('11%'),
  },
  avatar: {
    width: wp('9.5%'),
    height: wp('9.5%'),
    borderRadius: wp('4.75%'),
    backgroundColor: CM_COLORS.skeleton,
  },
  commentBody: {
    flex: 1,
    marginLeft: wp('3%'),
    paddingRight: wp('2%'),
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  username: {
    fontSize: wp('3.7%'),
    fontWeight: '700',
    color: CM_COLORS.text,
  },
  time: {
    fontSize: wp('3.2%'),
    color: CM_COLORS.meta,
    fontWeight: '500',
  },
  ownerBadge: {
    fontSize: wp('3%'),
    color: CM_COLORS.owner,
    fontWeight: '600',
  },
  commentText: {
    marginTop: hp('0.35%'),
    fontSize: wp('3.8%'),
    lineHeight: wp('5.4%'),
    color: CM_COLORS.text,
    fontWeight: '400',
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp('0.6%'),
    gap: 14,
  },
  replyBtn: {
    fontSize: wp('3.2%'),
    color: CM_COLORS.reply,
    fontWeight: '600',
  },
  viewRepliesBtn: {
    fontSize: wp('3.2%'),
    color: CM_COLORS.muted,
    fontWeight: '600',
    marginTop: hp('0.5%'),
  },
  likeColumn: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 2,
    minWidth: wp('8%'),
  },
  likeCount: {
    fontSize: wp('2.8%'),
    color: CM_COLORS.muted,
    marginTop: 4,
    fontWeight: '600',
  },
  footerWrap: {
    backgroundColor: CM_COLORS.sheetBg,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: CM_COLORS.border,
    paddingHorizontal: wp('4%'),
    paddingTop: hp('1.2%'),
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
      },
      android: { elevation: 12 },
    }),
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: wp('2.5%'),
  },
  inputShell: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CM_COLORS.inputBg,
    borderRadius: 999,
    paddingHorizontal: wp('4%'),
    minHeight: hp('5.4%'),
    maxHeight: hp('14%'),
  },
  input: {
    flex: 1,
    fontSize: wp('3.8%'),
    color: CM_COLORS.text,
    paddingVertical: Platform.OS === 'ios' ? hp('1.2%') : hp('1%'),
    maxHeight: hp('12%'),
  },
  inputAvatar: {
    width: wp('8.5%'),
    height: wp('8.5%'),
    borderRadius: wp('4.25%'),
    backgroundColor: CM_COLORS.skeleton,
  },
  sendBtn: {
    width: wp('9%'),
    height: wp('9%'),
    borderRadius: wp('4.5%'),
    backgroundColor: CM_COLORS.title,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp('0.2%'),
  },
  sendBtnDisabled: {
    backgroundColor: '#D1D5DB',
  },
  loginHint: {
    textAlign: 'center',
    color: CM_COLORS.muted,
    fontSize: wp('3.6%'),
    paddingVertical: hp('1.5%'),
  },
  emptyWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp('8%'),
    paddingHorizontal: wp('10%'),
  },
  emptyTitle: {
    marginTop: hp('2%'),
    fontSize: wp('4.2%'),
    fontWeight: '700',
    color: CM_COLORS.title,
  },
  emptySubtitle: {
    marginTop: hp('0.8%'),
    fontSize: wp('3.6%'),
    color: CM_COLORS.muted,
    textAlign: 'center',
    lineHeight: wp('5.2%'),
  },
  skeletonRow: {
    flexDirection: 'row',
    paddingVertical: hp('1.2%'),
    gap: wp('3%'),
  },
  skeletonCircle: {
    width: wp('9.5%'),
    height: wp('9.5%'),
    borderRadius: wp('4.75%'),
    backgroundColor: CM_COLORS.skeleton,
  },
  skeletonBlock: {
    flex: 1,
    gap: 8,
  },
  skeletonLine: {
    height: hp('1.2%'),
    borderRadius: 6,
    backgroundColor: CM_COLORS.skeleton,
  },
});
