import { Platform, StyleSheet } from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import { fontText } from '../../../utils/fonts';

export const BLOCKED_COLORS = {
  bg: '#FFFFFF',
  card: '#FFFFFF',
  border: '#E5E7EB',
  text: '#111827',
  muted: '#6B7280',
  faint: '#9CA3AF',
  primary: '#0000FF',
  primaryTint: '#E8EFFF',
  danger: '#DC2626',
  thumbBg: '#F3F4F6',
};

export const blockedUsersStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: BLOCKED_COLORS.bg },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp('8%'),
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    minHeight: 48,
  },
  headerTitle: {
    ...fontText.semibold13,
    fontSize: 17,
    color: BLOCKED_COLORS.text,
    flex: 1,
    textAlign: 'center',
  },
  headerBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: wp('5%'),
    paddingBottom: 12,
  },
  searchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: BLOCKED_COLORS.border,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 10 : 6,
    backgroundColor: '#FFF',
  },
  searchInput: {
    flex: 1,
    ...fontText.regular12,
    fontSize: 15,
    color: BLOCKED_COLORS.text,
  },
  listContent: {
    paddingHorizontal: wp('5%'),
    paddingTop: 4,
    paddingBottom: hp('4%'),
  },
  emptyWrap: {
    alignItems: 'center',
    paddingTop: hp('8%'),
    paddingHorizontal: 16,
  },
  emptyTitle: {
    ...fontText.semibold13,
    fontSize: 16,
    color: BLOCKED_COLORS.text,
    textAlign: 'center',
    marginTop: 16,
  },
  emptySubtitle: {
    ...fontText.regular12,
    fontSize: 13,
    color: BLOCKED_COLORS.muted,
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 19,
  },
  emptyHint: {
    ...fontText.regular12,
    fontSize: 13,
    color: BLOCKED_COLORS.muted,
    textAlign: 'center',
    marginTop: 24,
  },
  errorText: {
    ...fontText.medium13,
    color: BLOCKED_COLORS.danger,
    textAlign: 'center',
    marginBottom: 12,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: BLOCKED_COLORS.thumbBg,
  },
  rowBody: { flex: 1, minWidth: 0 },
  rowName: {
    ...fontText.semibold13,
    fontSize: 15,
    color: BLOCKED_COLORS.text,
  },
  rowMeta: {
    ...fontText.regular12,
    fontSize: 12,
    color: BLOCKED_COLORS.muted,
    marginTop: 2,
  },
  actionPill: {
    minWidth: 84,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: BLOCKED_COLORS.primary,
  },
  actionPillText: {
    ...fontText.semibold13,
    fontSize: 14,
    color: '#FFFFFF',
  },
  footerLoader: { marginVertical: 16 },
  // --- Block confirm bottom sheet ---
  sheetBg: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  sheetHandle: {
    backgroundColor: '#D1D5DB',
    width: 44,
    height: 4,
  },
  sheetContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  sheetHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetTitle: {
    ...fontText.bold13,
    fontSize: 20,
    color: BLOCKED_COLORS.text,
  },
  sheetTargetWrap: {
    alignItems: 'center',
    marginTop: 18,
  },
  sheetAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: BLOCKED_COLORS.thumbBg,
  },
  sheetTargetName: {
    ...fontText.bold13,
    fontSize: 17,
    color: BLOCKED_COLORS.text,
    marginTop: 10,
  },
  sheetTargetRole: {
    ...fontText.regular12,
    fontSize: 13,
    color: BLOCKED_COLORS.muted,
    marginTop: 2,
  },
  sheetWarning: {
    ...fontText.semibold13,
    fontSize: 14,
    color: BLOCKED_COLORS.primary,
    textAlign: 'center',
    marginTop: 20,
    lineHeight: 20,
  },
  sheetBulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginTop: 16,
  },
  sheetBulletText: {
    ...fontText.regular12,
    flex: 1,
    fontSize: 14,
    color: BLOCKED_COLORS.text,
    lineHeight: 20,
  },
  sheetButtonsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 28,
  },
  sheetButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    borderRadius: 14,
    backgroundColor: BLOCKED_COLORS.primaryTint,
  },
  sheetButtonText: {
    ...fontText.semibold13,
    fontSize: 16,
    color: BLOCKED_COLORS.primary,
  },
});
