import { Platform, StyleSheet } from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import { fontText } from '../../../utils/fonts';

export const PAYMENT_COLORS = {
  bg: '#FFFFFF',
  bgDark: '#0B1020',
  card: '#F8FAFF',
  text: '#111827',
  muted: '#6B7280',
  primary: '#0000FF',
  navy: '#1B2B6B',
  border: '#E5EAF6',
  success: '#16A34A',
  successBg: '#ECFDF5',
  danger: '#DC2626',
  dangerBg: '#FEF2F2',
  warning: '#D97706',
  warningBg: '#FFFBEB',
  cancelled: '#6B7280',
  cancelledBg: '#F3F4F6',
};

export const paymentStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: PAYMENT_COLORS.bg },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp('8%'),
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    minHeight: 48,
  },
  headerTitle: {
    ...fontText.semibold13,
    fontSize: 17,
    color: PAYMENT_COLORS.text,
    flex: 1,
    textAlign: 'center',
  },
  headerBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressTrack: {
    height: 3,
    backgroundColor: PAYMENT_COLORS.border,
    width: '100%',
  },
  progressFill: {
    height: 3,
    backgroundColor: PAYMENT_COLORS.primary,
  },
  statusIconWrap: {
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp('2.2%'),
  },
  statusTitle: {
    ...fontText.bold16,
    fontSize: 24,
    color: PAYMENT_COLORS.navy,
    textAlign: 'center',
    marginBottom: 8,
  },
  statusSubtitle: {
    ...fontText.regular12,
    fontSize: 14,
    color: PAYMENT_COLORS.muted,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: hp('2.5%'),
  },
  card: {
    width: '100%',
    backgroundColor: PAYMENT_COLORS.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: PAYMENT_COLORS.border,
    padding: 16,
    marginBottom: hp('2%'),
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  rowLabel: {
    ...fontText.regular12,
    fontSize: 13,
    color: PAYMENT_COLORS.muted,
  },
  rowValue: {
    ...fontText.semibold13,
    fontSize: 13,
    color: PAYMENT_COLORS.navy,
    maxWidth: '58%',
    textAlign: 'right',
  },
  primaryBtn: {
    width: '100%',
    backgroundColor: PAYMENT_COLORS.primary,
    borderRadius: 999,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  primaryBtnText: {
    ...fontText.bold16,
    fontSize: 16,
    color: '#FFFFFF',
  },
  secondaryBtn: {
    width: '100%',
    borderRadius: 999,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: PAYMENT_COLORS.border,
    marginBottom: 10,
  },
  secondaryBtnText: {
    ...fontText.semibold13,
    fontSize: 15,
    color: PAYMENT_COLORS.navy,
  },
  linkBtn: {
    paddingVertical: 10,
  },
  linkBtnText: {
    ...fontText.semibold13,
    fontSize: 14,
    color: PAYMENT_COLORS.primary,
    textAlign: 'center',
  },
  btnDisabled: { opacity: 0.45 },
  errorText: {
    ...fontText.medium13,
    color: PAYMENT_COLORS.danger,
    textAlign: 'center',
    marginBottom: 12,
  },
  searchInput: {
    borderWidth: 1,
    borderColor: PAYMENT_COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 12 : 8,
    marginHorizontal: wp('5%'),
    marginBottom: 12,
    ...fontText.regular12,
    fontSize: 14,
    color: PAYMENT_COLORS.text,
    backgroundColor: '#FFF',
  },
  listContent: {
    paddingHorizontal: wp('5%'),
    paddingBottom: hp('4%'),
  },
  txCard: {
    borderWidth: 1,
    borderColor: PAYMENT_COLORS.border,
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    backgroundColor: '#FFF',
  },
  txTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  txOrder: {
    ...fontText.semibold13,
    fontSize: 14,
    color: PAYMENT_COLORS.navy,
    flex: 1,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  badgeText: {
    ...fontText.bold13,
    fontSize: 10,
    letterSpacing: 0.4,
  },
  txAmount: {
    ...fontText.bold16,
    fontSize: 18,
    color: PAYMENT_COLORS.navy,
    marginBottom: 4,
  },
  txMeta: {
    ...fontText.regular12,
    fontSize: 12,
    color: PAYMENT_COLORS.muted,
  },
  txActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  txActionText: {
    ...fontText.semibold13,
    fontSize: 13,
    color: PAYMENT_COLORS.primary,
  },
});
