import { Platform, StyleSheet } from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import { fontText } from '../../../utils/fonts';

export const BUY_PKG_COLORS = {
  bg: '#FFFFFF',
  title: '#1B2B6B',
  secureTitle: '#2C4AA8',
  text: '#111827',
  muted: '#6B7280',
  meta: '#8B95B5',
  border: '#E5EAF6',
  cardBorder: '#D7DFF5',
  storageBg: '#EEF2FF',
  storageBorder: '#C7D2FE',
  priceBlue: '#1B2B6B',
  primary: '#0000FF',
  link: '#0000FF',
  bullet: '#4F6BFF',
  divider: '#E8EDF8',
  planBorder: '#D1D5DB',
  planSelectedBg: '#0000FF',
  checkbox: '#0000FF',
};

export const buyPackageStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: BUY_PKG_COLORS.bg },
  content: {
    paddingHorizontal: wp('5%'),
    paddingTop: hp('1%'),
    paddingBottom: hp('14%'),
  },
  secureTitle: {
    ...fontText.semibold13,
    fontSize: 20,
    color: BUY_PKG_COLORS.secureTitle,
    textAlign: 'center',
    marginBottom: hp('2%'),
  },
  listingCard: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: BUY_PKG_COLORS.border,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#FFF',
    marginBottom: hp('2.2%'),
    ...Platform.select({
      ios: {
        shadowColor: '#1B2B6B',
        shadowOpacity: 0.05,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 3 },
      },
      android: { elevation: 1 },
    }),
  },
  listingImage: {
    width: wp('28%'),
    minHeight: 108,
    backgroundColor: '#E5E7EB',
  },
  listingBody: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'space-between',
  },
  listingTitle: {
    ...fontText.bold13,
    fontSize: 15,
    color: BUY_PKG_COLORS.text,
  },
  listingCategory: {
    ...fontText.regular12,
    color: BUY_PKG_COLORS.muted,
    marginTop: 2,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaText: {
    ...fontText.regular12,
    color: BUY_PKG_COLORS.meta,
  },
  listingPrice: {
    ...fontText.bold13,
    fontSize: 15,
    color: BUY_PKG_COLORS.primary,
    textAlign: 'right',
    marginTop: 8,
  },
  sectionHint: {
    ...fontText.medium13,
    fontSize: 14,
    color: BUY_PKG_COLORS.secureTitle,
    textAlign: 'center',
    marginBottom: hp('1.4%'),
  },
  storageCard: {
    borderWidth: 1.5,
    borderColor: BUY_PKG_COLORS.storageBorder,
    backgroundColor: BUY_PKG_COLORS.storageBg,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 12,
    marginBottom: hp('2.2%'),
  },
  storageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: BUY_PKG_COLORS.checkbox,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    backgroundColor: '#FFF',
  },
  checkboxChecked: {
    backgroundColor: BUY_PKG_COLORS.checkbox,
  },
  storageTitle: {
    ...fontText.bold13,
    fontSize: 15,
    color: BUY_PKG_COLORS.text,
    flex: 1,
  },
  storagePrice: {
    ...fontText.bold13,
    fontSize: 15,
    color: BUY_PKG_COLORS.priceBlue,
  },
  storageDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: BUY_PKG_COLORS.storageBorder,
    marginVertical: 12,
  },
  storageDesc: {
    ...fontText.regular12,
    fontSize: 13,
    lineHeight: 18,
    color: BUY_PKG_COLORS.secureTitle,
    marginBottom: 10,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
    paddingRight: 4,
  },
  bulletDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: BUY_PKG_COLORS.bullet,
    marginTop: 6,
    marginRight: 10,
  },
  bulletText: {
    ...fontText.regular12,
    fontSize: 13,
    lineHeight: 19,
    color: BUY_PKG_COLORS.secureTitle,
    flex: 1,
  },
  learnMore: {
    ...fontText.bold13,
    fontSize: 12,
    color: BUY_PKG_COLORS.link,
    textAlign: 'right',
    marginTop: 6,
    letterSpacing: 0.4,
  },
  plansRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  planChip: {
    flex: 1,
    minWidth: 0,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: BUY_PKG_COLORS.planBorder,
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    paddingHorizontal: 4,
    alignItems: 'center',
  },
  planChipSelected: {
    backgroundColor: BUY_PKG_COLORS.planSelectedBg,
    borderColor: BUY_PKG_COLORS.planSelectedBg,
  },
  planWeek: {
    ...fontText.medium12,
    fontSize: 11,
    color: BUY_PKG_COLORS.muted,
    marginBottom: 4,
    textAlign: 'center',
  },
  planWeekSelected: {
    color: 'rgba(255,255,255,0.9)',
  },
  planAmount: {
    ...fontText.bold13,
    fontSize: 12,
    color: BUY_PKG_COLORS.priceBlue,
    textAlign: 'center',
  },
  planAmountSelected: {
    color: '#FFFFFF',
  },
  storageBreakdown: {
    marginTop: 14,
    gap: 8,
  },
  breakdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  breakdownLabel: {
    ...fontText.medium12,
    fontSize: 13,
    color: BUY_PKG_COLORS.secureTitle,
  },
  breakdownValue: {
    ...fontText.medium13,
    fontSize: 13,
    color: BUY_PKG_COLORS.secureTitle,
  },
  breakdownTotalLabel: {
    ...fontText.bold13,
    fontSize: 15,
    color: BUY_PKG_COLORS.priceBlue,
  },
  breakdownTotalValue: {
    ...fontText.bold16,
    fontSize: 16,
    color: BUY_PKG_COLORS.priceBlue,
  },
  orderTitle: {
    ...fontText.bold16,
    fontSize: 17,
    color: BUY_PKG_COLORS.text,
    marginBottom: 12,
  },
  orderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  orderLabel: {
    ...fontText.medium13,
    fontSize: 14,
    color: BUY_PKG_COLORS.secureTitle,
  },
  orderValue: {
    ...fontText.medium13,
    fontSize: 14,
    color: BUY_PKG_COLORS.secureTitle,
  },
  discountLink: {
    ...fontText.semibold13,
    fontSize: 14,
    color: BUY_PKG_COLORS.link,
    marginTop: 2,
    marginBottom: 12,
  },
  orderDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: BUY_PKG_COLORS.divider,
    marginBottom: 12,
  },
  totalLabel: {
    ...fontText.bold16,
    fontSize: 17,
    color: BUY_PKG_COLORS.priceBlue,
  },
  totalValue: {
    ...fontText.bold16,
    fontSize: 18,
    color: BUY_PKG_COLORS.priceBlue,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: wp('5%'),
    paddingTop: 12,
    backgroundColor: BUY_PKG_COLORS.bg,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: BUY_PKG_COLORS.divider,
  },
  payBtn: {
    backgroundColor: BUY_PKG_COLORS.primary,
    borderRadius: 999,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  payBtnText: {
    ...fontText.bold16,
    fontSize: 16,
    color: '#FFFFFF',
  },
  loadingPlans: {
    paddingVertical: 16,
    alignItems: 'center',
  },
});
