import { Platform, StyleSheet } from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import { fontText } from '../../../utils/fonts';

export const PLACE_AD_COLORS = {
  background: '#FFFFFF',
  title: '#1B2B6B',
  subtitle: '#2C3E8A',
  cardBorder: '#D7DFF5',
  cardBorderSelected: '#0000FF',
  radioBorder: '#C5CEE8',
  radioSelected: '#0000FF',
  packageName: '#1F2937',
  price: '#1B2B6B',
  vat: '#8B95B5',
  feature: '#3B4A8A',
  check: '#22C55E',
  checkBg: '#E8F9EF',
  recommendedBg: '#1B2B6B',
  recommendedText: '#FFFFFF',
  divider: '#E8EDF8',
  confirmBg: '#0000FF',
  skip: '#1B2B6B',
  skeleton: '#E8EDF8',
};

export const placeAdStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: PLACE_AD_COLORS.background,
  },
  content: {
    paddingHorizontal: wp('5%'),
    paddingTop: hp('1%'),
    paddingBottom: hp('14%'),
  },
  subtitle: {
    ...fontText.medium13,
    fontSize: 15,
    color: PLACE_AD_COLORS.subtitle,
    textAlign: 'center',
    marginBottom: hp('2.2%'),
    lineHeight: 22,
  },
  card: {
    borderWidth: 1.5,
    borderColor: PLACE_AD_COLORS.cardBorder,
    borderRadius: 18,
    paddingHorizontal: wp('4.5%'),
    paddingTop: hp('1.8%'),
    paddingBottom: hp('1.6%'),
    marginBottom: hp('1.6%'),
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#1B2B6B',
        shadowOpacity: 0.04,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
      },
      android: { elevation: 1 },
    }),
  },
  cardSelected: {
    borderColor: PLACE_AD_COLORS.cardBorderSelected,
    backgroundColor: '#FAFBFF',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: PLACE_AD_COLORS.radioBorder,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  radioOuterSelected: {
    borderColor: PLACE_AD_COLORS.radioSelected,
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: PLACE_AD_COLORS.radioSelected,
  },
  packageName: {
    ...fontText.bold16,
    fontSize: 17,
    color: PLACE_AD_COLORS.packageName,
    flex: 1,
  },
  recommendedBadge: {
    backgroundColor: PLACE_AD_COLORS.recommendedBg,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  recommendedText: {
    ...fontText.bold13,
    fontSize: 10,
    color: PLACE_AD_COLORS.recommendedText,
    letterSpacing: 0.6,
  },
  priceBlock: {
    marginTop: hp('1.2%'),
    marginBottom: hp('1.1%'),
    minHeight: hp('7.5%'),
    justifyContent: 'center',
    overflow: 'hidden',
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    zIndex: 1,
  },
  currency: {
    ...fontText.semibold13,
    fontSize: 16,
    color: PLACE_AD_COLORS.price,
    marginRight: 6,
    marginBottom: 6,
  },
  amount: {
    ...fontText.bold16,
    fontSize: 42,
    lineHeight: 48,
    color: PLACE_AD_COLORS.price,
    letterSpacing: -1,
  },
  vat: {
    ...fontText.medium12,
    fontSize: 13,
    color: PLACE_AD_COLORS.vat,
    marginLeft: 8,
    marginBottom: 8,
  },
  doodleWrap: {
    position: 'absolute',
    right: -wp('3%'),
    top: -hp('1.2%'),
    bottom: -hp('1.2%'),
    width: wp('52%'),
    alignItems: 'flex-end',
    justifyContent: 'center',
    zIndex: 0,
  },
  doodleImage: {
    width: wp('50%'),
    height: hp('100%'),
    opacity: 0.11,
    transform: [{ rotate: '-18deg' }],
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: PLACE_AD_COLORS.divider,
    marginBottom: hp('1.3%'),
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: hp('1%'),
    paddingRight: 4,
  },
  checkWrap: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: PLACE_AD_COLORS.checkBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    marginTop: 1,
  },
  featureText: {
    ...fontText.regular12,
    fontSize: 14,
    lineHeight: 20,
    color: PLACE_AD_COLORS.feature,
    flex: 1,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp('5%'),
    paddingTop: hp('1.4%'),
    backgroundColor: PLACE_AD_COLORS.background,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: PLACE_AD_COLORS.divider,
    gap: 16,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: -3 },
      },
      android: { elevation: 10 },
    }),
  },
  skipBtn: {
    paddingVertical: 12,
    paddingHorizontal: 8,
    minWidth: 64,
  },
  skipText: {
    ...fontText.semibold13,
    fontSize: 16,
    color: PLACE_AD_COLORS.skip,
  },
  confirmBtn: {
    flex: 1,
    backgroundColor: PLACE_AD_COLORS.confirmBg,
    borderRadius: 999,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  confirmBtnDisabled: {
    opacity: 0.45,
  },
  confirmText: {
    ...fontText.bold16,
    fontSize: 16,
    color: '#FFFFFF',
  },
  centerWrap: {
    paddingVertical: hp('8%'),
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorText: {
    ...fontText.medium13,
    color: '#DC2626',
    textAlign: 'center',
    marginBottom: 12,
  },
  retryText: {
    ...fontText.semibold13,
    color: PLACE_AD_COLORS.confirmBg,
  },
  skeletonCard: {
    height: hp('22%'),
    borderRadius: 18,
    backgroundColor: PLACE_AD_COLORS.skeleton,
    marginBottom: hp('1.6%'),
  },
});
