import { Platform, StyleSheet } from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

export const CP_COLORS = {
  bg: '#FFFFFF',
  text: '#111827',
  muted: '#6B7280',
  border: '#E5E7EB',
  primary: '#2563EB',
  primaryDark: '#1D4ED8',
  tipBg: '#EFF6FF',
  tipText: '#1E40AF',
  error: '#DC2626',
  cardBorder: '#D1D5DB',
};

export const cpStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: CP_COLORS.bg },
  header: {
    marginTop: Platform.OS === 'ios' ? 0 : 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp('2%'),
    paddingVertical: hp('1.2%'),
  },
  headerBtn: {
    width: wp('10%'),
    height: wp('10%'),
    alignItems: 'center',
    justifyContent: 'center',
  },
  leftSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  title: {
    fontSize: 18, //wp('5%'),
    fontWeight: '600',
    color: CP_COLORS.text,
    letterSpacing: -0.3,
  },
  subtitle: {
    marginTop: hp('0.6%'),
    fontSize: wp('3.8%'),
    color: CP_COLORS.muted,
    lineHeight: wp('5.4%'),
  },
  content: {
    flex: 1,
    paddingHorizontal: wp('4.5%'),
  },
  footer: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: CP_COLORS.border,
    paddingHorizontal: wp('4.5%'),
    paddingTop: hp('1.2%'),
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: -3 },
      },
      android: { elevation: 8 },
    }),
  },
  progressText: {
    color: CP_COLORS.muted,
    fontWeight: '600',
    fontSize: wp('3.5%'),
  },
  primaryBtn: {
    backgroundColor: CP_COLORS.primary,
    borderRadius: 999,
    paddingHorizontal: wp('8%'),
    paddingVertical: hp('1.4%'),
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  primaryBtnText: { color: '#fff', fontWeight: '700', fontSize: wp('3.8%') },
  primaryBtnDisabled: { backgroundColor: '#93C5FD' },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp('3.5%'),
    marginTop: hp('2%'),
  },
  categoryCard: {
    width: wp('42%'),
    aspectRatio: 1.05,
    borderRadius: 16,
    padding: wp('4%'),
    justifyContent: 'space-between',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  categoryCardSelected: { borderColor: CP_COLORS.primary },
  categoryTitle: {
    fontWeight: '700',
    fontSize: wp('4%'),
    color: CP_COLORS.text,
  },
  listItem: {
    paddingVertical: hp('2%'),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: CP_COLORS.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  listItemText: {
    fontSize: wp('4.2%'),
    fontWeight: '600',
    color: CP_COLORS.text,
  },
  mediaCard: {
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: CP_COLORS.primary,
    borderRadius: 14,
    paddingVertical: hp('3.5%'),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFF',
    marginBottom: hp('1.5%'),
  },
  mediaCardTitle: {
    marginTop: hp('1%'),
    fontWeight: '700',
    color: CP_COLORS.primary,
    fontSize: wp('4%'),
  },
  mediaCardSub: { marginTop: 4, color: CP_COLORS.muted, fontSize: wp('3.2%') },
  orText: {
    textAlign: 'center',
    color: CP_COLORS.muted,
    marginVertical: hp('0.8%'),
    fontWeight: '600',
  },
  tipBox: {
    marginTop: hp('2%'),
    backgroundColor: CP_COLORS.tipBg,
    borderRadius: 12,
    padding: wp('4%'),
    flexDirection: 'row',
    gap: 10,
  },
  tipText: {
    flex: 1,
    color: CP_COLORS.tipText,
    fontSize: wp('3.5%'),
    lineHeight: wp('5%'),
  },
  inputLabel: {
    fontWeight: '500',
    color: CP_COLORS.tipText,
    marginBottom: 8,
    fontSize: wp('3.9%'),
  },
  input: {
    borderWidth: 1,
    borderColor: CP_COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 14 : 10,
    fontSize: wp('3.8%'),
    color: CP_COLORS.text,
    backgroundColor: '#F2F2FB',
  },
  textarea: { minHeight: hp('16%'), textAlignVertical: 'top' },
  sectionTitle: {
    fontSize: wp('4.8%'),
    fontWeight: '800',
    color: CP_COLORS.text,
    marginBottom: hp('1.2%'),
  },
  summaryCard: {
    borderWidth: 1,
    borderColor: CP_COLORS.border,
    borderRadius: 14,
    padding: wp('4%'),
    backgroundColor: '#FAFAFA',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: CP_COLORS.border,
  },
  summaryLabel: { color: CP_COLORS.muted, fontSize: wp('3.4%') },
  summaryValue: {
    color: CP_COLORS.text,
    fontWeight: '700',
    fontSize: wp('3.4%'),
    maxWidth: '58%',
    textAlign: 'right',
  },
  imageGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  imageTile: {
    width: '31%',
    aspectRatio: 1,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#E5E7EB',
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  chip: {
    borderWidth: 1,
    borderColor: CP_COLORS.border,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#fff',
  },
  chipActive: { backgroundColor: '#EFF6FF', borderColor: CP_COLORS.primary },
  chipText: { color: CP_COLORS.text, fontWeight: '600', fontSize: wp('3.3%') },
  chipTextActive: { color: CP_COLORS.primary },
  centerState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp('4%'),
    gap: 10,
  },
  stateTitle: {
    color: CP_COLORS.text,
    fontSize: wp('4.2%'),
    fontWeight: '700',
    textAlign: 'center',
  },
  stateText: {
    color: CP_COLORS.muted,
    fontSize: wp('3.6%'),
    textAlign: 'center',
    lineHeight: wp('5.2%'),
  },
  retryButton: {
    marginTop: 8,
    backgroundColor: CP_COLORS.primary,
    borderRadius: 10,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  retryButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: wp('3.5%'),
  },
});
