import { Platform, StyleSheet } from 'react-native';
import { AppTheme } from '../../theme/colors';

export const getLocationMapPickerStyles = (theme: AppTheme) =>
  StyleSheet.create({
    wrapper: {
      marginTop: 24,
      marginBottom: 8,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: '#1E2A5A',
      marginBottom: 14,
    },
    card: {
      backgroundColor: theme.background,
      borderRadius: 20,
      padding: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: '#E5E7EB',
      ...Platform.select({
        ios: {
          shadowColor: '#0F172A',
          shadowOpacity: 0.06,
          shadowRadius: 14,
          shadowOffset: { width: 0, height: 6 },
        },
        android: { elevation: 3 },
      }),
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 8,
    },
    cardTitle: {
      flex: 1,
      fontSize: 16,
      fontWeight: '700',
      color: theme.text,
      lineHeight: 22,
    },
    infoIconWrap: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 1.5,
      borderColor: '#111827',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 1,
    },
    cardDescription: {
      fontSize: 14,
      lineHeight: 20,
      color: theme.subText,
      marginBottom: 14,
    },
    mapShell: {
      height: 220,
      borderRadius: 14,
      overflow: 'hidden',
      backgroundColor: '#E8EEF5',
    },
    map: {
      ...StyleSheet.absoluteFill,
      width: '100%',
      height: '100%',
    },
    mapOverlay: {
      ...StyleSheet.absoluteFill,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(248,250,252,0.72)',
    },
    mapTapOverlay: {
      ...StyleSheet.absoluteFill,
      zIndex: 5,
    },
    currentLocationBtn: {
      position: 'absolute',
      right: 12,
      bottom: 12,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.background,
      alignItems: 'center',
      justifyContent: 'center',
      ...Platform.select({
        ios: {
          shadowColor: '#0F172A',
          shadowOpacity: 0.12,
          shadowRadius: 8,
          shadowOffset: { width: 0, height: 3 },
        },
        android: { elevation: 5 },
      }),
    },
    statusText: {
      marginTop: 10,
      fontSize: 12,
      lineHeight: 16,
      color: theme.subText,
    },
    fieldBlock: {
      marginTop: 16,
    },
    fieldLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: '#6B7280',
      marginBottom: 8,
    },
    inputShell: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 14,
      backgroundColor: '#F5F7FF',
      borderWidth: 1,
      borderColor: '#E4E9F7',
      paddingHorizontal: 14,
      minHeight: Platform.OS === 'ios' ? 52 : 54,
    },
    input: {
      flex: 1,
      color: theme.text,
      fontSize: 15,
      paddingVertical: Platform.OS === 'ios' ? 14 : 10,
    },
    optionalText: {
      marginLeft: 8,
      fontSize: 13,
      fontWeight: '500',
      color: '#9CA3AF',
    },
    tipBox: {
      marginTop: 18,
      borderRadius: 14,
      backgroundColor: '#EAF2FF',
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    tipText: {
      fontSize: 13,
      lineHeight: 19,
      color: '#1E3A8A',
      fontWeight: '500',
    },
    // Legacy modal styles kept for LocationMapPickerModal / interactive panel
    modalRoot: {
      flex: 1,
      backgroundColor: theme.background,
    },
    modalHeader: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 8,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: '#E5E7EB',
    },
    modalHeaderBtn: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalHeaderTitle: {
      flex: 1,
      textAlign: 'center',
      fontSize: 22,
      fontWeight: '600',
      color: theme.text,
      lineHeight: 28,
    },
    modalMapWrap: {
      flex: 1,
      margin: 0,
      borderRadius: 0,
      overflow: 'hidden',
      backgroundColor: '#E8EEF5',
    },
    modalBottomCard: {
      marginHorizontal: 12,
      marginBottom: 12,
      borderRadius: 16,
      padding: 14,
      backgroundColor: theme.background,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: '#E5E7EB',
    },
    modalAddressLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.subText,
      marginBottom: 4,
    },
    modalAddressValue: {
      fontSize: 18,
      fontWeight: '600',
      lineHeight: 24,
      color: theme.text,
    },
    modalCoords: {
      marginTop: 4,
      fontSize: 12,
      color: theme.subText,
    },
    modalActionRow: {
      marginTop: 12,
      flexDirection: 'row',
      gap: 10,
    },
    modalCancelBtn: {
      flex: 1,
      minHeight: 48,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#D1D5DB',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFFFFF',
    },
    modalCancelBtnText: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.text,
    },
    modalConfirmBtn: {
      flex: 1.2,
      minHeight: 48,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#0000FF',
    },
    modalConfirmBtnText: {
      fontSize: 15,
      fontWeight: '700',
      color: '#FFFFFF',
    },
  });
