import { Platform, StyleSheet } from 'react-native';
import { AppTheme } from '../../theme/colors';

export const getNotificationTheme = (theme: AppTheme) => ({
  bg: theme.background,
  text: theme.text,
  muted: theme.subText,
  primary: theme.primary,
  card: theme.card,
  border: `${theme.subText}22`,
  unreadBg: '#F5F3FF',
  danger: theme.danger,
  success: '#10B981',
  pillActiveBg: '#EEF2FF',
  pillActiveText: theme.primary,
  skeleton: theme.card,
});

export type NotificationTheme = ReturnType<typeof getNotificationTheme>;

export const getNotificationStyles = (theme: AppTheme) => {
  const c = getNotificationTheme(theme);

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: c.bg,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
      backgroundColor: c.bg,
    },
    headerTitle: {
      flex: 1,
      fontSize: 20,
      fontWeight: '800',
      color: c.text,
      marginLeft: 8,
    },
    summaryCard: {
      marginHorizontal: 16,
      marginTop: 14,
      marginBottom: 10,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.bg,
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOpacity: 0.05,
          shadowRadius: 8,
          shadowOffset: { width: 0, height: 2 },
        },
        android: { elevation: 1 },
      }),
    },
    avatarStack: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    stackAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
      borderWidth: 2,
      borderColor: c.bg,
      backgroundColor: c.card,
    },
    stackAvatarOverlap: {
      marginLeft: -10,
    },
    summaryTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: c.text,
    },
    summarySubtitle: {
      fontSize: 13,
      color: c.muted,
      marginTop: 2,
    },
    tabsRow: {
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 16,
      paddingBottom: 12,
    },
    tabPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.bg,
    },
    tabPillActive: {
      backgroundColor: c.pillActiveBg,
      borderColor: c.primary,
    },
    tabText: {
      fontSize: 14,
      fontWeight: '600',
      color: c.muted,
    },
    tabTextActive: {
      color: c.pillActiveText,
    },
    tabBadge: {
      minWidth: 20,
      height: 20,
      borderRadius: 10,
      paddingHorizontal: 6,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#111827',
    },
    tabBadgeText: {
      color: '#FFFFFF',
      fontSize: 11,
      fontWeight: '700',
    },
    sectionHeader: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: c.card,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    sectionHeaderText: {
      fontSize: 12,
      fontWeight: '800',
      color: c.muted,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    row: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 14,
      backgroundColor: c.bg,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    rowUnread: {
      backgroundColor: c.unreadBg,
    },
    rowContent: {
      flex: 1,
      minWidth: 0,
    },
    rowText: {
      fontSize: 14,
      lineHeight: 20,
      color: c.text,
    },
    rowName: {
      fontWeight: '700',
      color: c.text,
    },
    rowMeta: {
      marginTop: 4,
      fontSize: 12,
      color: c.muted,
    },
    replyBtn: {
      marginTop: 6,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    replyText: {
      fontSize: 12,
      color: c.muted,
      fontWeight: '600',
    },
    thumb: {
      width: 52,
      height: 52,
      borderRadius: 10,
      backgroundColor: c.card,
      marginTop: 2,
    },
    actionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 10,
    },
    confirmBtn: {
      paddingHorizontal: 18,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: c.primary,
      minWidth: 92,
      alignItems: 'center',
      justifyContent: 'center',
    },
    confirmText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '700',
    },
    rejectBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarWrap: {
      position: 'relative',
    },
    avatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: c.card,
    },
    typeBadge: {
      position: 'absolute',
      right: -2,
      bottom: -2,
      width: 20,
      height: 20,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: c.bg,
    },
    systemIcon: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 28,
      paddingVertical: 56,
      gap: 8,
    },
    emptyTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: c.text,
      textAlign: 'center',
    },
    emptySubtitle: {
      fontSize: 14,
      color: c.muted,
      textAlign: 'center',
      lineHeight: 20,
    },
    errorWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: 24,
      gap: 12,
    },
    errorText: {
      color: c.danger,
      textAlign: 'center',
      fontSize: 14,
    },
    footerLoader: {
      paddingVertical: 18,
      alignItems: 'center',
    },
    skeletonRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    skeletonAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: c.skeleton,
    },
    skeletonLine: {
      height: 12,
      borderRadius: 6,
      backgroundColor: c.skeleton,
    },
    followScreenSectionTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: c.text,
      paddingHorizontal: 16,
      paddingTop: 18,
      paddingBottom: 8,
    },
    followRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
      backgroundColor: c.bg,
    },
    followActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    acceptBtn: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: c.primary,
      minWidth: 84,
      alignItems: 'center',
    },
    deleteBtn: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: c.card,
    },
    deleteText: {
      color: c.primary,
      fontSize: 13,
      fontWeight: '700',
    },
  });
};

export type NotificationStyles = ReturnType<typeof getNotificationStyles>;
