import { useMemo } from 'react';
import { StyleSheet } from 'react-native';
import { AppTheme } from '../theme/colors';
import { useAppTheme } from './useAppTheme';

export const CREATE_POST_PRIMARY = '#0000FF';

export const getCreatePostStyles = (theme: AppTheme) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: theme.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 4,
      minHeight: 48,
      paddingBottom: 4,
    },
    headerBtn: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerHelpBtn: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitleSpacer: { flex: 1 },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      fontSize: 17,
      fontWeight: '600',
      color: theme.text,
      marginHorizontal: 4,
    },
    title: {
      fontSize: 18,
      fontWeight: '700',
      color: '#21357C',
      letterSpacing: -0.3,
      justifyContent: 'center',
      alignSelf: 'center',
    },
    subtitle: {
      marginTop: 8,
      fontSize: 15,
      marginBottom: 12,
      color: theme.subText,
      lineHeight: 22,
      justifyContent: 'center',
      alignSelf: 'center',
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.text,
      marginBottom: 12,
      marginTop: 8,
    },
    photoLimitText: {
      fontSize: 16,
      fontWeight: '500',
      color: theme.subText,
    },
    content: { flexGrow: 1, paddingHorizontal: 16 },
    categoryScrollContent: { paddingTop: 8, paddingBottom: 24 },
    footer: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.subText + '33',
      paddingHorizontal: 16,
      paddingTop: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    progressText: { color: theme.subText, fontWeight: '600', fontSize: 14 },
    primaryBtn: {
      backgroundColor: CREATE_POST_PRIMARY,
      borderRadius: 999,
      paddingHorizontal: 24,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    primaryBtnDisabled: { opacity: 0.45 },
    primaryBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },
    categoryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      marginTop: 20,
    },
    categoryCard: {
      minHeight: 108,
      borderRadius: 14,
      padding: 16,
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: 'transparent',
    },
    categoryCardSelected: { borderColor: CREATE_POST_PRIMARY },
    categoryTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.text,
      marginTop: 12,
    },
    listItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.subText + '33',
    },
    listItemText: { fontSize: 16, fontWeight: '600', color: theme.text },
    orText: {
      textAlign: 'center',
      color: theme.subText,
      marginVertical: 12,
      fontWeight: '600',
    },
    tipBox: {
      flexDirection: 'row',
      gap: 10,
      backgroundColor: theme.card,
      borderRadius: 12,
      padding: 14,
      marginTop: 16,
    },
    tipText: { flex: 1, color: theme.text, lineHeight: 20, fontSize: 14 },
    centerState: { alignItems: 'center', paddingVertical: 32 },
    stateTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.text,
      marginBottom: 8,
    },
    stateText: { fontSize: 14, color: theme.subText, textAlign: 'center' },
    retryButton: {
      marginTop: 16,
      backgroundColor: CREATE_POST_PRIMARY,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 999,
    },
    retryButtonText: { color: '#fff', fontWeight: '700' },
    photoActionRow: { flexDirection: 'row', gap: 10, marginBottom: 16 , marginTop: 16},
    secondaryBtn: {
      flex: 1,
      borderWidth: 1,
      borderColor: '#E9EEFF',
      backgroundColor: '#E9EEFF',
      borderRadius: 24,
      paddingVertical: 12,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 6,
    },
    secondaryBtnText: { color: '#21357C', fontWeight: '700' },
    secondaryBtnDisabled: { opacity: 0.45 },
    helperBanner: {
      backgroundColor: '#FFF4E5',
      borderRadius: 10,
      padding: 12,
      marginBottom: 16,
    },
    helperBannerText: { color: '#92400E', fontSize: 13, lineHeight: 18 },
    reviewCard: {
      backgroundColor: theme.card,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
    },
    reviewCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    reviewCardTitle: { fontSize: 16, fontWeight: '700', color: theme.text },
    reviewEdit: { color: CREATE_POST_PRIMARY, fontWeight: '700', fontSize: 14 },
    reviewRow: { flexDirection: 'row', marginBottom: 8 },
    reviewLabel: { width: '42%', color: theme.subText, fontSize: 14 },
    reviewValue: {
      flex: 1,
      color: theme.text,
      fontSize: 15,
      fontWeight: '500',
    },
    skeleton: {
      height: 108,
      borderRadius: 14,
      backgroundColor: theme.card,
      marginBottom: 12,
    },
    skeletonLine: {
      height: 52,
      borderRadius: 14,
      backgroundColor: theme.card,
      marginBottom: 12,
    },
    imageGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    imageTile: {
      width: '31%',
      aspectRatio: 1,
      borderRadius: 10,
      overflow: 'hidden',
      backgroundColor: theme.card,
    },
    mediaCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.subText + '44',
      borderStyle: 'dashed',
      padding: 20,
      alignItems: 'center',
      backgroundColor: theme.card,
      marginBottom: 12,
    },
    mediaCardTitle: {
      marginTop: 10,
      fontSize: 16,
      fontWeight: '700',
      color: theme.text,
    },
    mediaCardSub: { marginTop: 4, fontSize: 13, color: theme.subText },
  });

export type CreatePostStyles = ReturnType<typeof getCreatePostStyles>;

export const useCreatePostStyles = () => {
  const theme = useAppTheme();
  return useMemo(() => getCreatePostStyles(theme), [theme]);
};
