import { Platform, StyleSheet } from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

export const PE_COLORS = {
  bg: '#FFFFFF',
  text: '#111827',
  muted: '#6B7280',
  border: '#E5E7EB',
  inputBg: '#F9FAFB',
  primary: '#2563EB',
  primaryLight: '#EFF6FF',
  dashed: '#93C5FD',
  error: '#DC2626',
};

export const peStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: PE_COLORS.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('1.2%'),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PE_COLORS.border,
  },
  headerTitle: { fontSize: wp('4.8%'), fontWeight: '800', color: PE_COLORS.text },
  headerBtn: { width: wp('10%'), height: wp('10%'), alignItems: 'center', justifyContent: 'center' },
  scroll: { paddingHorizontal: wp('4.5%'), paddingBottom: hp('14%') },
  verifiedCard: {
    marginTop: hp('2%'),
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: PE_COLORS.dashed,
    borderRadius: 14,
    paddingVertical: hp('2%'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  verifiedText: { color: PE_COLORS.primary, fontWeight: '700', fontSize: wp('4%') },
  sectionTitle: { fontSize: wp('4.6%'), fontWeight: '800', color: PE_COLORS.text, marginTop: hp('2.4%') },
  sectionSubtitle: { fontSize: wp('3.4%'), color: PE_COLORS.muted, marginTop: 4, marginBottom: hp('1.2%') },
  inputWrap: { marginBottom: hp('1.4%') },
  inputShell: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: PE_COLORS.border,
    borderRadius: 14,
    backgroundColor: PE_COLORS.inputBg,
    paddingHorizontal: 14,
    minHeight: hp('6%'),
  },
  inputShellFocused: { borderColor: PE_COLORS.primary, backgroundColor: '#fff' },
  input: { flex: 1, fontSize: wp('3.8%'), color: PE_COLORS.text, paddingVertical: Platform.OS === 'ios' ? 14 : 10 },
  errorText: { color: PE_COLORS.error, fontSize: wp('3.2%'), marginTop: 4 },
  radioRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: hp('1.2%'), gap: 12 },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#9CA3AF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterActive: { borderColor: PE_COLORS.primary },
  radioInner: { width: 12, height: 12, borderRadius: 6, backgroundColor: PE_COLORS.primary },
  radioLabel: { fontSize: wp('3.8%'), color: PE_COLORS.text, fontWeight: '600' },
  addressCard: {
    borderWidth: 1,
    borderColor: PE_COLORS.border,
    borderRadius: 14,
    padding: wp('4%'),
    marginBottom: hp('1.4%'),
    backgroundColor: '#fff',
  },
  addressTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  addressLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  addressLabel: { fontWeight: '700', fontSize: wp('3.8%'), color: PE_COLORS.text },
  addressText: { marginTop: hp('1%'), color: PE_COLORS.muted, fontSize: wp('3.5%'), lineHeight: wp('5%') },
  addressActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 16, marginTop: hp('1.2%') },
  addressAction: { color: PE_COLORS.primary, fontWeight: '700', fontSize: wp('3.5%') },
  addLocationBtn: {
    marginTop: hp('1%'),
    backgroundColor: PE_COLORS.primaryLight,
    borderRadius: 999,
    paddingVertical: hp('1.4%'),
    alignItems: 'center',
  },
  addLocationText: { color: '#1E40AF', fontWeight: '700', fontSize: wp('3.6%') },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: wp('4.5%'),
    paddingTop: hp('1.2%'),
    backgroundColor: '#fff',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: PE_COLORS.border,
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 8, shadowOffset: { width: 0, height: -3 } },
      android: { elevation: 8 },
    }),
  },
  submitBtn: {
    backgroundColor: PE_COLORS.primary,
    borderRadius: 14,
    paddingVertical: hp('1.8%'),
    alignItems: 'center',
  },
  submitBtnDisabled: { backgroundColor: '#93C5FD' },
  submitText: { color: '#fff', fontWeight: '800', fontSize: wp('4.2%') },
  addressField: {
    borderWidth: 1,
    borderColor: PE_COLORS.border,
    borderRadius: 14,
    backgroundColor: PE_COLORS.inputBg,
    paddingHorizontal: 16,
    paddingVertical: Platform.OS === 'ios' ? 16 : 12,
    fontSize: wp('3.8%'),
    color: PE_COLORS.text,
    marginBottom: hp('1.2%'),
  },
  labelChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: PE_COLORS.border,
    backgroundColor: '#FFFFFF',
  },
  labelChipActive: {
    borderColor: PE_COLORS.primary,
    backgroundColor: PE_COLORS.primaryLight,
  },
  labelChipText: { fontSize: wp('3.5%'), fontWeight: '700', color: PE_COLORS.muted },
  labelChipTextActive: { color: PE_COLORS.primary },
  labelChipCustom: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: PE_COLORS.dashed,
    backgroundColor: '#FFFFFF',
  },
  labelChipCustomText: { fontSize: wp('3.5%'), fontWeight: '700', color: PE_COLORS.primary },
  mapPreviewCard: {
    borderWidth: 1,
    borderColor: PE_COLORS.border,
    borderRadius: 16,
    padding: 16,
    marginBottom: hp('2%'),
    backgroundColor: '#FFFFFF',
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOpacity: 0.06,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
      },
      android: { elevation: 3 },
    }),
  },
  mapPreviewTitle: { fontSize: wp('4%'), fontWeight: '800', color: PE_COLORS.text },
  mapPreviewSubtitle: {
    fontSize: wp('3.2%'),
    color: PE_COLORS.muted,
    marginTop: 4,
    marginBottom: hp('1.4%'),
    lineHeight: wp('4.6%'),
  },
  mapPreviewShell: {
    height: hp('22%'),
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#E8EEF5',
  },
  mapShowBtn: {
    position: 'absolute',
    alignSelf: 'center',
    top: '50%',
    marginTop: -20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOpacity: 0.12,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
      },
      android: { elevation: 6 },
    }),
  },
  mapShowBtnText: { color: PE_COLORS.primary, fontWeight: '800', fontSize: wp('3.6%') },
  defaultToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: hp('1%'),
    marginBottom: hp('1%'),
  },
});
