import { Platform, StyleSheet } from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
//import { QV_COLORS } from '../../presentation/components/productQuickView/productQuickViewStyles.ts';

export const PD_COLORS = {
  bg: '#F8FAFC',
  card: '#FFFFFF',
  text: '#111827',
  muted: '#6B7280',
  lightMuted: '#9CA3AF',
  primary: '#2563EB',
  price: '#0026FF',
  available: '#22C55E',
  divider: '#E5E7EB',
  overlay: 'rgba(255,255,255,0.88)',
  glass: 'rgba(255,255,255,0.92)',
};

export const pdStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: PD_COLORS.bg },
  scrollContent: { paddingBottom: hp('14%') },
  section: {
    backgroundColor: PD_COLORS.card,
    marginHorizontal: wp('4%'),
    marginTop: hp('1.4%'),
    borderRadius: 16,
    padding: wp('4.5%'),
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
      },
      android: { elevation: 3 },
    }),
  },


  detail_section: {
    //backgroundColor: PD_COLORS.card,
    //marginHorizontal: wp('4%'),
    marginTop: hp('1.4%'),
    borderRadius: 16,
    padding: wp('1.5%'),
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
      },
      android: { elevation: 3 },
    }),
  },
  sectionTitle: {
    fontSize: wp('4.6%'),
    fontWeight: '800',
    color: PD_COLORS.text,
    marginBottom: hp('1.2%'),
  },
  floatingBtn: {
    width: wp('10%'),
    height: wp('10%'),
    borderRadius: wp('5%'),
    backgroundColor: PD_COLORS.glass,
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
      },
      android: { elevation: 4 },
    }),
  },
  headerCard: {
    marginTop: -hp('4%'),
    marginHorizontal: wp('4%'),
    backgroundColor: PD_COLORS.card,
    borderRadius: 18,
    padding: wp('4.5%'),
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 6 },
      },
      android: { elevation: 6 },
    }),
  },
  badgeRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: hp('1%'),
    justifyContent: 'space-between',
  },
  priceBadge: {
    backgroundColor: PD_COLORS.price,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  priceBadgeText: { color: '#fff', fontWeight: '800', fontSize: wp('3.5%') },
  availableBadge: {
    backgroundColor: '#1EB700',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  availableText: { color: '#FFF', fontWeight: '700', fontSize: wp('3.2%') },
  productTitle: {
    fontSize: wp('4.6%'),
    fontWeight: '800',
    color: PD_COLORS.text,
    lineHeight: wp('6.8%'),
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    marginTop: hp('1.2%'),
  },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  metaText: { color: PD_COLORS.muted, fontSize: wp('3.2%'), fontWeight: '600' },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: hp('1.6%'),
    flexWrap: 'wrap',
  },
  statPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: PD_COLORS.divider,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#fff',
  },
  statPillText: {
    fontWeight: '700',
    color: PD_COLORS.text,
    fontSize: wp('3.2%'),
  },
  overviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp('3%'),
  },
  overviewCell: {
    width: '30%',
    minWidth: wp('25%'),
    marginBottom: hp('1.2%'),
  },
  overviewLabel: {
    color: PD_COLORS.lightMuted,
    fontSize: wp('2.9%'),
    marginBottom: 4,
  },
  overviewValue: {
    color: PD_COLORS.text,
    fontWeight: '700',
    fontSize: wp('3.1%'),
  },
  readMore: {
    color: PD_COLORS.primary,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: hp('1%'),
    fontSize: wp('3.6%'),
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: hp('1.4%'),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PD_COLORS.divider,
  },
  featureTitle: {
    fontWeight: '700',
    color: PD_COLORS.text,
    fontSize: wp('3.7%'),
    flex: 1,
  },
  featureBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#EFF6FF',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  featureBadgeText: {
    color: PD_COLORS.primary,
    fontWeight: '700',
    fontSize: wp('3.1%'),
  },
  mapCard: {
    height: hp('18%'),
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#fff',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
      },
      android: { elevation: 3 },
    }),
  },
  sellerRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  sellerAvatar: {
    width: wp('12%'),
    height: wp('12%'),
    borderRadius: wp('6%'),
    backgroundColor: '#E5E7EB',
  },
  similarCard: {
    width: wp('58%'),
    marginRight: wp('3%'),
    backgroundColor: '#fff',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: PD_COLORS.divider,
  },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: hp('1.3%'),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PD_COLORS.divider,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#fff',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: PD_COLORS.divider,
    paddingHorizontal: wp('4%'),
    paddingTop: hp('1.2%'),
    flexDirection: 'row',
    gap: wp('3%'),
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: -4 },
      },
      android: { elevation: 12 },
    }),
  },
  skeleton: { backgroundColor: '#E5E7EB' },
});
